update rust-up bootstrapper

diff --git a/bootstrap/bootstrap-rust-up b/bootstrap/bootstrap-rust-up
--- a/bootstrap/bootstrap-rust-up
+++ b/bootstrap/bootstrap-rust-up
@@ -17,14 +17,37 @@ set -u
 
 RUSTUP_UPDATE_ROOT="https://static.rust-lang.org/rustup/dist"
 
+#XXX: If you change anything here, please make the same changes in setup_mode.rs
+usage() {
+    cat 1>&2 <<EOF
+rustup-init 1.0.0 (408ed84 2017-02-11)
+The installer for rustup
+
+USAGE:
+    rustup-init [FLAGS] [OPTIONS]
+
+FLAGS:
+    -v, --verbose           Enable verbose output
+    -y                      Disable confirmation prompt.
+        --no-modify-path    Don't configure the PATH environment variable
+    -h, --help              Prints help information
+    -V, --version           Prints version information
+
+OPTIONS:
+        --default-host <default-host>              Choose a default host triple
+        --default-toolchain <default-toolchain>    Choose a default toolchain to install
+        --default-toolchain none                   Do not install any toolchains
+EOF
+}
+
 main() {
+    need_cmd uname
     need_cmd curl
     need_cmd mktemp
     need_cmd chmod
     need_cmd mkdir
     need_cmd rm
     need_cmd rmdir
-    need_cmd printf
 
     get_architecture || return 1
     local _arch="$RETVAL"
@@ -42,21 +65,25 @@ main() {
     local _dir="$(mktemp -d 2>/dev/null || ensure mktemp -d -t rustup)"
     local _file="$_dir/rustup-init$_ext"
 
-    printf "\33[1minfo:\33[0m downloading installer\n"
-
-    ensure mkdir -p "$_dir"
-    ensure curl -sSfL "$_url" -o "$_file"
-    ensure chmod u+x "$_file"
-    if [ ! -x "$_file" ]; then
-        echo "Cannot execute $_file (likely because of mounting /tmp as noexec)."
-        echo "Please copy the file to a location where you can execute binaries and run ./rustup-init$_ext."
-        exit 1
+    local _ansi_escapes_are_valid=false
+    if [ -t 2 ]; then
+        if [ "${TERM+set}" = 'set' ]; then
+            case "$TERM" in
+                xterm*|rxvt*|urxvt*|linux*|vt*)
+                    _ansi_escapes_are_valid=true
+                ;;
+            esac
+        fi
     fi
 
     # check if we have to use /dev/tty to prompt the user
     local need_tty=yes
     for arg in "$@"; do
         case "$arg" in
+            -h|--help)
+                usage
+                exit 0
+                ;;
             -y)
                 # user wants to skip the prompt -- we don't need /dev/tty
                 need_tty=no
@@ -66,19 +93,35 @@ main() {
         esac
     done
 
+    if $_ansi_escapes_are_valid; then
+        printf "\33[1minfo:\33[0m downloading installer\n" 1>&2
+    else
+        printf '%s\n' 'info: downloading installer' 1>&2
+    fi
+
+    ensure mkdir -p "$_dir"
+    ensure curl -sSfL "$_url" -o "$_file"
+    ensure chmod u+x "$_file"
+    if [ ! -x "$_file" ]; then
+        printf '%s\n' "Cannot execute $_file (likely because of mounting /tmp as noexec)." 1>&2
+        printf '%s\n' "Please copy the file to a location where you can execute binaries and run ./rustup-init$_ext." 1>&2
+        exit 1
+    fi
+
+
 
     if [ "$need_tty" = "yes" ]; then
         # The installer is going to want to ask for confirmation by
         # reading stdin.  This script was piped into `sh` though and
         # doesn't have stdin to pass to its children. Instead we're going
         # to explicitly connect /dev/tty to the installer's stdin.
-        if [ ! -e "/dev/tty" ]; then
-            err "/dev/tty does not exist"
+        if [ ! -t 1 ]; then
+            err "Unable to run interactively. Run with -y to accept defaults, --help for additional options"
         fi
 
-        run "$_file" "$@" < /dev/tty
+        ignore "$_file" "$@" < /dev/tty
     else
-        run "$_file" "$@"
+        ignore "$_file" "$@"
     fi
 
     local _retval=$?
@@ -89,10 +132,53 @@ main() {
     return "$_retval"
 }
 
+get_bitness() {
+    need_cmd head
+    # Architecture detection without dependencies beyond coreutils.
+    # ELF files start out "\x7fELF", and the following byte is
+    #   0x01 for 32-bit and
+    #   0x02 for 64-bit.
+    # The printf builtin on some shells like dash only supports octal
+    # escape sequences, so we use those.
+    local _current_exe_head=$(head -c 5 /proc/self/exe )
+    if [ "$_current_exe_head" = "$(printf '\177ELF\001')" ]; then
+        echo 32
+    elif [ "$_current_exe_head" = "$(printf '\177ELF\002')" ]; then
+        echo 64
+    else
+        err "unknown platform bitness"
+    fi
+}
+
+get_endianness() {
+    local cputype=$1
+    local suffix_eb=$2
+    local suffix_el=$3
+
+    # detect endianness without od/hexdump, like get_bitness() does.
+    need_cmd head
+    need_cmd tail
+
+    local _current_exe_endianness="$(head -c 6 /proc/self/exe | tail -c 1)"
+    if [ "$_current_exe_endianness" = "$(printf '\001')" ]; then
+        echo "${cputype}${suffix_el}"
+    elif [ "$_current_exe_endianness" = "$(printf '\002')" ]; then
+        echo "${cputype}${suffix_eb}"
+    else
+        err "unknown platform endianness"
+    fi
+}
+
 get_architecture() {
 
     local _ostype="$(uname -s)"
     local _cputype="$(uname -m)"
+
+    if [ "$_ostype" = Linux ]; then
+        if [ "$(uname -o)" = Android ]; then
+            local _ostype=Android
+        fi
+    fi
 
     if [ "$_ostype" = Darwin -a "$_cputype" = i386 ]; then
         # Darwin `uname -s` lies
@@ -103,12 +189,20 @@ get_architecture() {
 
     case "$_ostype" in
 
+        Android)
+            local _ostype=linux-android
+            ;;
+
         Linux)
             local _ostype=unknown-linux-gnu
             ;;
 
         FreeBSD)
             local _ostype=unknown-freebsd
+            ;;
+
+        NetBSD)
+            local _ostype=unknown-netbsd
             ;;
 
         DragonFly)
@@ -137,16 +231,27 @@ get_architecture() {
 
         xscale | arm)
             local _cputype=arm
+            if [ "$_ostype" = "linux-android" ]; then
+                local _ostype=linux-androideabi
+            fi
             ;;
 
         armv6l)
             local _cputype=arm
-            local _ostype="${_ostype}eabihf"
+            if [ "$_ostype" = "linux-android" ]; then
+                local _ostype=linux-androideabi
+            else
+                local _ostype="${_ostype}eabihf"
+            fi
             ;;
 
-        armv7l)
+        armv7l | armv8l)
             local _cputype=armv7
-            local _ostype="${_ostype}eabihf"
+            if [ "$_ostype" = "linux-android" ]; then
+                local _ostype=linux-androideabi
+            else
+                local _ostype="${_ostype}eabihf"
+            fi
             ;;
 
         aarch64)
@@ -155,6 +260,26 @@ get_architecture() {
 
         x86_64 | x86-64 | x64 | amd64)
             local _cputype=x86_64
+            ;;
+
+        mips)
+            local _cputype="$(get_endianness $_cputype "" 'el')"
+            ;;
+
+        mips64)
+            local _bitness="$(get_bitness)"
+            if [ $_bitness = "32" ]; then
+                if [ $_ostype = "unknown-linux-gnu" ]; then
+                    # 64-bit kernel with 32-bit userland
+                    # endianness suffix is appended later
+                    local _cputype=mips
+                fi
+            else
+                # only n64 ABI is supported for now
+                local _ostype="${_ostype}abi64"
+            fi
+
+            local _cputype="$(get_endianness $_cputype "" 'el')"
             ;;
 
         ppc)
@@ -176,15 +301,7 @@ get_architecture() {
 
     # Detect 64-bit linux with 32-bit userland
     if [ $_ostype = unknown-linux-gnu -a $_cputype = x86_64 ]; then
-        need_cmd head
-        # Architecture detection without dependencies beyond coreutils.
-        # ELF files start out "\x7fELF", and the following byte is
-        #   0x01 for 32-bit and
-        #   0x02 for 64-bit.
-        # The printf builtin on some shells like dash only supports octal
-        # escape sequences, so we use those.
-        local _current_exe_head=$(head -c 5 /proc/self/exe )
-        if [ "$_current_exe_head" = "$(printf '\177ELF\001')" ]; then
+        if [ "$(get_bitness)" = "32" ]; then
             local _cputype=i686
         fi
     fi
@@ -206,10 +323,6 @@ get_architecture() {
 
 say() {
     echo "rustup: $1"
-}
-
-say_err() {
-    say "$1" >&2
 }
 
 err() {
@@ -243,17 +356,7 @@ ensure() {
 # intentionally ignored. Usually, because it's being executed
 # as part of error handling.
 ignore() {
-    run "$@"
-}
-
-# Runs a command and prints it to stderr if it fails.
-run() {
     "$@"
-    local _retval=$?
-    if [ $_retval != 0 ]; then
-        say_err "command failed: $*"
-    fi
-    return $_retval
 }
 
 main "$@" || exit 1
