remove oh-my-fish, will use fisherman instead

diff --git a/bootstrap/bootstrap-rvm b/bootstrap/bootstrap-rvm
--- a/bootstrap/bootstrap-rvm
+++ b/bootstrap/bootstrap-rvm
@@ -31,6 +31,7 @@ fail() { log "\nERROR: $*\n" ; exit 1 ; }
 rvm_install_commands_setup()
 {
   \which which >/dev/null 2>&1 || fail "Could not find 'which' command, make sure it's available first before continuing installation."
+  \which grep >/dev/null 2>&1 || fail "Could not find 'grep' command, make sure it's available first before continuing installation."
   if
     [[ -z "${rvm_tar_command:-}" ]] && builtin command -v gtar >/dev/null
   then
@@ -62,13 +63,13 @@ rvm_install_commands_setup()
               then sudo_10=sudo
               elif \which /opt/csw/bin/sudo >/dev/null 2>&1
               then sudo_10=/opt/csw/bin/sudo
-              else fail "sudo is required but not found. You may install sudo from OpenCSW repository (http://opencsw.org/about)"
+              else fail "sudo is required but not found. You may install sudo from OpenCSW repository (https://www.opencsw.org/about)"
               fi
-              pkginfo -q CSWpkgutil || $sudo_10 pkgadd -a $rvm_path/config/solaris/noask -d http://get.opencsw.org/now CSWpkgutil
-              sudo /opt/csw/bin/pkgutil -iy CSWgtar -t http://mirror.opencsw.org/opencsw/unstable
+              pkginfo -q CSWpkgutil || $sudo_10 pkgadd -a $rvm_path/config/solaris/noask -d https://get.opencsw.org/now CSWpkgutil
+              sudo /opt/csw/bin/pkgutil -iy CSWgtar -t https://mirror.opencsw.org/opencsw/unstable
             else
-              pkginfo -q CSWpkgutil || pkgadd -a $rvm_path/config/solaris/noask -d http://get.opencsw.org/now CSWpkgutil
-              /opt/csw/bin/pkgutil -iy CSWgtar -t http://mirror.opencsw.org/opencsw/unstable
+              pkginfo -q CSWpkgutil || pkgadd -a $rvm_path/config/solaris/noask -d https://get.opencsw.org/now CSWpkgutil
+              /opt/csw/bin/pkgutil -iy CSWgtar -t https://mirror.opencsw.org/opencsw/unstable
             fi
             rvm_tar_command=/opt/csw/bin/gtar
             ;;
@@ -768,7 +769,7 @@ It looks you are one of the happy Ubuntu users,
 RVM packaged by Ubuntu is old and broken,
 follow this link for details how to fix:
 
-  http://stackoverflow.com/a/9056395/497756
+  https://stackoverflow.com/a/9056395/497756
 
 "
       [[ "${rvm_uses_broken_ubuntu_path:-no}" == "yes" ]] || exit 3
