update bootstrapers

diff --git a/bootstrap/bootstrap-rust-with-cargo b/bootstrap/bootstrap-rust-with-cargo
--- a/bootstrap/bootstrap-rust-with-cargo
+++ b/bootstrap/bootstrap-rust-with-cargo
@@ -41,10 +41,10 @@
 # to indicate the error code won't be handled, and `ensure`, which
 # prints the command on failure, and also exits the process.
 #
-# Pass errors on on: `run cmd arg1 arg2 || return 1`. `run` will run
+# Pass errors on: `run cmd arg1 arg2 || return 1`. `run` will run
 # the command, printing it if it fails; the `|| return 1` passes the
 # error on to the caller. `ensure cmd arg1 arg1`, runs the command,
-# printing it if it fails, and termining execution.
+# printing it if it fails, and terminating execution.
 #
 # Don't make typos. You just have to be better than that.
 #
@@ -517,7 +517,7 @@ EOF
 	fi
     fi
 
-    
+
     if [ "$_uninstall" = false ]; then
 	cat <<EOF
 
@@ -1013,11 +1013,11 @@ get_architecture() {
 	# $SHELL does not exist in standard 'sh', so probably only exists
 	# if configure is running in an interactive bash shell. /usr/bin/env
 	# exists *everywhere*.
-	local _bin_to_probe="$SHELL"
-	if [ -z "$_bin_to_probe" -a -e "/usr/bin/env" ]; then
+	local _bin_to_probe="${SHELL-bogus_shell}"
+	if [ ! -e "$_bin_to_probe" -a -e "/usr/bin/env" ]; then
 	    _bin_to_probe="/usr/bin/env"
 	fi
-	if [ -n "$_bin_to_probe" ]; then
+	if [ -e "$_bin_to_probe" ]; then
 	    file -L "$_bin_to_probe" | grep -q "x86[_-]64"
 	    if [ $? != 0 ]; then
 		local _cputype=i686
@@ -1318,7 +1318,7 @@ Usage: rustup.sh [--verbose]
 
 Options:
 
-     --channel=(stable|beta|nightly)   Install from channel (default beta)
+     --channel=(stable|beta|nightly)   Install from channel (default stable)
      --date=<YYYY-MM-DD>               Install from archives
      --revision=<version-number>       Install a specific release
      --spec=<toolchain-spec>           Install from toolchain spec
@@ -1327,6 +1327,7 @@ Options:
      --disable-ldconfig                Do not run ldconfig on Linux
      --disable-sudo                    Do not run installer under sudo
      --save                            Save downloads for future reuse
+     --yes, -y                         Disable the interactive mode
 '
 }
 
@@ -1353,7 +1354,7 @@ err() {
 
 need_cmd() {
     if ! command -v "$1" > /dev/null 2>&1
-    then err "need $1"
+    then err "need '$1' (command not found)"
     fi
 }
 
