bugfix

diff --git a/install/linux/install-vcpkg b/install/linux/install-vcpkg
--- a/install/linux/install-vcpkg
+++ b/install/linux/install-vcpkg
@@ -4,10 +4,17 @@
 
 if [ -z $1 ] ; then
     FOLDER=~/projects/tools
-    mkdir -p $FOLDER
-fi
+else
     FOLDER=$1
-cd
+fi
+
+if [ -z $FOLDER ] ; then
+    echo "Invalid Install Folder"
+    exit 1
+fi
+
+echo "Install Folder: $FOLDER"
+mkdir -p $FOLDER
 
 if [ -d ${FOLDER}/vcpkg ] ; then
     cd ${FOLDER}/vcpkg
